### ISSUE TITLE
not requiring attributes on every relationship returned from endpoint

### ISSUE THREAD

**Issue by timjcook** [frank06/ember-data-save-relationships#14]
Referring to `updateRecord`, see [here](https://github.com/frank06/ember-data-save-relationships/blob/master/addon/index.js#L63-L80), currently it is required that the `json` variable has an `attributes` key implying that every relationship needs this key set, even if it is empty.
I'm finding this is not the case in my app (currently using `ember-cli-mirage`). My problems are solved by wrapping everything in that method in a conditional:

```
if (json.attributes) {
  ...
}
```

Happy to PR if you like the above approach, saves me stubbing out that key with an empty option.

Thanks for the addon @frank06, big Ember Igniter fan! 🔥 🎉

**Comment by frank06** [comment]
Thanks @timjcook :) that should fix it

**Comment by timjcook** [comment]
Thanks mate, that looks like it will be great.
